// Mock data for the CareerVerse platform

export const studentMockData = {
  profile: {
    id: "1",
    name: "Alex Rivera",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop",
    level: 12,
    xp: 2450,
    xpToNextLevel: 3000,
    streak: 7,
    badges: [
      { id: "1", name: "Early Bird", icon: "🌅", color: "yellow" },
      { id: "2", name: "Quiz Master", icon: "🧠", color: "purple" },
      { id: "3", name: "Community Hero", icon: "⭐", color: "pink" },
      { id: "4", name: "Career Explorer", icon: "🚀", color: "blue" },
    ],
  },
  recentActivity: [
    { id: "1", type: "lesson", title: "Completed: Resume Writing 101", xp: 50, time: "2h ago" },
    { id: "2", type: "quiz", title: "Aced: Interview Skills Quiz", xp: 100, time: "5h ago" },
    { id: "3", type: "community", title: "Posted in Career Discussions", xp: 25, time: "1d ago" },
  ],
};

export const lessons = [
  {
    id: "1",
    title: "Resume Writing 101",
    category: "Professional Skills",
    duration: "8 min",
    xp: 50,
    completed: true,
    thumbnail: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&h=300&fit=crop",
    difficulty: "Beginner",
  },
  {
    id: "2",
    title: "Mastering LinkedIn",
    category: "Networking",
    duration: "12 min",
    xp: 75,
    completed: true,
    thumbnail: "https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=400&h=300&fit=crop",
    difficulty: "Intermediate",
  },
  {
    id: "3",
    title: "Interview Body Language",
    category: "Interview Prep",
    duration: "10 min",
    xp: 60,
    completed: false,
    thumbnail: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop",
    difficulty: "Beginner",
  },
  {
    id: "4",
    title: "Salary Negotiation Tactics",
    category: "Career Growth",
    duration: "15 min",
    xp: 100,
    completed: false,
    thumbnail: "https://images.unsplash.com/photo-1554224311-beee460c201f?w=400&h=300&fit=crop",
    difficulty: "Advanced",
  },
  {
    id: "5",
    title: "Building Your Personal Brand",
    category: "Professional Skills",
    duration: "20 min",
    xp: 125,
    completed: false,
    thumbnail: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop",
    difficulty: "Intermediate",
  },
  {
    id: "6",
    title: "Remote Work Best Practices",
    category: "Work Culture",
    duration: "10 min",
    xp: 60,
    completed: false,
    thumbnail: "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=400&h=300&fit=crop",
    difficulty: "Beginner",
  },
];

export const communityPosts = [
  {
    id: "1",
    author: {
      name: "Sarah Chen",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
      role: "student",
      level: 15,
    },
    title: "Just landed my first internship! Here's how I did it 🎉",
    content: "After months of applying and preparing, I finally got an offer from a tech startup. Happy to share my journey and tips!",
    category: "Success Stories",
    upvotes: 234,
    comments: 45,
    time: "3h ago",
    tags: ["internship", "tech", "success"],
  },
  {
    id: "2",
    author: {
      name: "Marcus Johnson",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
      role: "mentor",
      isMentor: true,
      expertise: "Product Manager",
    },
    title: "[AMA] 10 years in Product Management - Ask me anything!",
    content: "Hey CareerVerse! I've been in product management for a decade, worked at 3 startups and 2 big tech companies. Here to answer your questions!",
    category: "AMA",
    upvotes: 567,
    comments: 123,
    time: "5h ago",
    tags: ["AMA", "product-management", "career-advice"],
  },
  {
    id: "3",
    author: {
      name: "Priya Sharma",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
      role: "student",
      level: 8,
    },
    title: "Best resources for learning UX Design?",
    content: "I'm transitioning into UX design and looking for recommendations on courses, books, or projects. What helped you the most?",
    category: "Career Discussions",
    upvotes: 89,
    comments: 34,
    time: "1d ago",
    tags: ["ux-design", "learning", "resources"],
  },
  {
    id: "4",
    author: {
      name: "David Kim",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
      role: "student",
      level: 22,
    },
    title: "The harsh reality of job hunting nobody tells you about",
    content: "Been searching for 6 months. Here are the things I wish someone had told me before I started...",
    category: "Real Talk",
    upvotes: 412,
    comments: 87,
    time: "2d ago",
    tags: ["job-search", "reality-check", "motivation"],
  },
];

export const careers = [
  {
    id: "1",
    title: "UX Designer",
    category: "Creative",
    type: "conventional",
    demand: "high",
    salary: "$70k - $120k",
    skills: ["Figma", "User Research", "Prototyping", "Design Thinking"],
    description: "Create user-friendly digital experiences",
    icon: "🎨",
    color: "pink",
  },
  {
    id: "2",
    title: "Data Scientist",
    category: "Tech",
    type: "conventional",
    demand: "very-high",
    salary: "$90k - $150k",
    skills: ["Python", "Machine Learning", "Statistics", "SQL"],
    description: "Turn data into actionable insights",
    icon: "📊",
    color: "blue",
  },
  {
    id: "3",
    title: "Content Creator",
    category: "Creative",
    type: "unconventional",
    demand: "high",
    salary: "$40k - $200k+",
    skills: ["Video Editing", "Social Media", "Storytelling", "SEO"],
    description: "Build audiences and create engaging content",
    icon: "📹",
    color: "purple",
  },
  {
    id: "4",
    title: "Product Manager",
    category: "Business",
    type: "conventional",
    demand: "high",
    salary: "$100k - $180k",
    skills: ["Strategy", "Communication", "Analytics", "Agile"],
    description: "Lead product vision and execution",
    icon: "🚀",
    color: "orange",
  },
  {
    id: "5",
    title: "Sustainability Consultant",
    category: "Environmental",
    type: "unconventional",
    demand: "growing",
    salary: "$60k - $110k",
    skills: ["ESG", "Carbon Accounting", "Strategy", "Compliance"],
    description: "Help companies become environmentally responsible",
    icon: "🌱",
    color: "green",
  },
  {
    id: "6",
    title: "Growth Hacker",
    category: "Marketing",
    type: "unconventional",
    demand: "high",
    salary: "$70k - $130k",
    skills: ["Analytics", "A/B Testing", "SEO", "Viral Marketing"],
    description: "Drive explosive user and revenue growth",
    icon: "📈",
    color: "yellow",
  },
];

export const mentors = [
  {
    id: "1",
    name: "Marcus Johnson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    title: "Senior Product Manager",
    company: "Tech Startup",
    expertise: ["Product Management", "Strategy", "Leadership"],
    bio: "10+ years in product. Helped launch 5 successful products. Passionate about mentoring the next generation.",
    availability: "Available",
    engagementScore: 95,
    totalSessions: 47,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Lisa Rodriguez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    title: "UX Design Lead",
    company: "Design Agency",
    expertise: ["UX Design", "Design Systems", "User Research"],
    bio: "Award-winning designer. Love helping designers find their unique style and career path.",
    availability: "Available",
    engagementScore: 88,
    totalSessions: 34,
    rating: 4.8,
  },
  {
    id: "3",
    name: "Raj Patel",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    title: "Engineering Manager",
    company: "Big Tech",
    expertise: ["Software Engineering", "Career Growth", "Technical Leadership"],
    bio: "Started as a junior dev, now leading a team of 20. Happy to share my journey.",
    availability: "Limited",
    engagementScore: 92,
    totalSessions: 61,
    rating: 5.0,
  },
];

export const adminStats = {
  overview: {
    totalUsers: 12847,
    activeToday: 3421,
    totalPosts: 5683,
    totalLessons: 127,
  },
  engagement: {
    avgStreakLength: 4.2,
    lessonsCompletedToday: 842,
    postsToday: 156,
    activeDiscussions: 234,
  },
  topUsers: [
    { name: "Alex Rivera", streak: 47, xp: 15420, avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop" },
    { name: "Sarah Chen", streak: 42, xp: 14230, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop" },
    { name: "David Kim", streak: 38, xp: 13890, avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop" },
  ],
  flaggedPosts: [
    { id: "1", title: "Inappropriate language in discussion", author: "User123", time: "10m ago", severity: "medium" },
    { id: "2", title: "Spam link posted", author: "SpamBot42", time: "1h ago", severity: "high" },
  ],
};